language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
sudo: false

script:
  - yarn shim:lint
  - yarn shim:build
  - yarn shim:test

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: "6"